version: '3'

services:
  queue:
    build:
      context: ./services/queue
      dockerfile: Dockerfile
    command: node index.js
    volumes:
      - .:/services/queue
    ports:
      - "4000:4000"
  announcements:
    build:
      context: ./services/announcements
      dockerfile: Dockerfile
    command: node index.js
    volumes:
      - .:/services/announcements
    ports:
      - "4001:4001"
    depends_on:
      - queue